Bl tabbed interface
tluu5/photogram-industrial pull request #4
Opened 2024-10-18 16:58 UTC by tluu5

2024-10-18 17:18 UTC, armstrca requested changes

2024-10-18 17:18 UTC, armstrca commented on app/views/users/liked.html.erb
> +  <div class="col md-6 offset-3">
change to `col-md-6 offset-3`

2024-10-18 17:18 UTC, armstrca commented on app/views/users/show.html.erb
> +  <div class="col md-6 offset-3">
change to col-md-6 offset-3

2024-10-18 17:55 UTC, jessjno approved these changes
you should run and search and replace to make sure you got all the 'col-md-6' ones correct

2024-10-18 17:55 UTC, jessjno commented on app/views/photos/_photo.html.erb
> +  <div class="col-md-6 offset-md-3">
good job fixing this one

2024-10-18 17:55 UTC, jessjno commented on app/controllers/comments_controller.rb
good job changing the redirect_to

2024-10-18 17:55 UTC, jessjno commented on app/views/users/show.html.erb
> +  <div class="col md-6 offset-3">
don't forget to add that first '-' in 'col-md-6'

2024-10-18 22:09 UTC, armstrca requested changes

2024-10-18 22:09 UTC, armstrca commented on config/routes.rb
Lines 11 through 13 are incomplete and result in errors like this:

```
There's a problem with your routes.rb file.

Missing :controller key on routes definition, please check your routes.

/workspaces/photogram-industrial/config/routes.rb:11
```

2024-10-21 21:52 UTC, armstrca approved these changes
Thanks for fixing routes.rb. Looks good.

2024-10-22 13:59 UTC, merged